-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-09-17 21:35:04 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
set echo on
SPOOL rcl_schema_output.txt

DROP TABLE author CASCADE CONSTRAINTS;

DROP TABLE author_catalogue CASCADE CONSTRAINTS;

DROP TABLE book CASCADE CONSTRAINTS;

DROP TABLE book_catalogue CASCADE CONSTRAINTS;

DROP TABLE book_copy CASCADE CONSTRAINTS;

DROP TABLE borrower CASCADE CONSTRAINTS;

DROP TABLE branch CASCADE CONSTRAINTS;

DROP TABLE catalogue_entry CASCADE CONSTRAINTS;

DROP TABLE lga CASCADE CONSTRAINTS;

DROP TABLE loan CASCADE CONSTRAINTS;

DROP TABLE manager CASCADE CONSTRAINTS;

DROP TABLE publisher CASCADE CONSTRAINTS;

DROP TABLE publisher_catalogue CASCADE CONSTRAINTS;

DROP TABLE reservation CASCADE CONSTRAINTS;

DROP TABLE subject CASCADE CONSTRAINTS;

DROP TABLE subject_catalogue CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE author (
    auth_id   CHAR(4) NOT NULL,
    auth_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN author.auth_id IS
    'author id';

COMMENT ON COLUMN author.auth_name IS
    'author name';

ALTER TABLE author ADD CONSTRAINT author_pk PRIMARY KEY ( auth_id );

CREATE TABLE author_catalogue (
    auth_id     CHAR(4) NOT NULL,
    cat_call_no VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN author_catalogue.auth_id IS
    'author id';

COMMENT ON COLUMN author_catalogue.cat_call_no IS
    'catalogue call number';

ALTER TABLE author_catalogue ADD CONSTRAINT author_catalogue_pk PRIMARY KEY ( auth_id,
                                                                              cat_call_no );

CREATE TABLE book (
    isbn_no   CHAR(13) NOT NULL,
    book_type CHAR(1) NOT NULL
);

ALTER TABLE book
    ADD CONSTRAINT "book type constraint" CHECK ( book_type IN ( 'H', 'L' ) );

COMMENT ON COLUMN book.isbn_no IS
    'isbn number of each book';

COMMENT ON COLUMN book.book_type IS
    'book type(H=hard cover, l=loose leaf)';

ALTER TABLE book ADD CONSTRAINT book_catalogue_pk PRIMARY KEY ( isbn_no );

CREATE TABLE book_catalogue (
    cat_call_no VARCHAR2(20) NOT NULL,
    isbn_no     CHAR(13) NOT NULL
);

COMMENT ON COLUMN book_catalogue.cat_call_no IS
    'catalogue call number';

COMMENT ON COLUMN book_catalogue.isbn_no IS
    'isbn number of each book';

ALTER TABLE book_catalogue ADD CONSTRAINT book_catalogue_pkv1 PRIMARY KEY ( cat_call_no,
                                                                            isbn_no );

CREATE TABLE book_copy (
    book_copy_sk CHAR(3) NOT NULL,
    copy_id      CHAR(4) NOT NULL,
    branch_code  CHAR(3) NOT NULL,
    isbn_no      CHAR(13) NOT NULL,
    copy_price   NUMBER(6, 2),
    copy_flag    CHAR(1) NOT NULL,
    copy_status  CHAR(1)
);

ALTER TABLE book_copy
    ADD CHECK ( copy_flag IN ( 'A', 'CR', 'L' ) );

ALTER TABLE book_copy
    ADD CHECK ( copy_status IN ( 'D', 'L', 'S' ) );

COMMENT ON COLUMN book_copy.book_copy_sk IS
    'book opy surrograte key';

COMMENT ON COLUMN book_copy.copy_id IS
    'book copy id';

COMMENT ON COLUMN book_copy.branch_code IS
    'branch_code';

COMMENT ON COLUMN book_copy.isbn_no IS
    'isbn number of each book';

COMMENT ON COLUMN book_copy.copy_price IS
    'book copy price';

COMMENT ON COLUMN book_copy.copy_flag IS
    'copy reserve flag (OC = On Counter Reserve, L = On Loan, A = Available for Loan)';

COMMENT ON COLUMN book_copy.copy_status IS
    'copy status (S = Stolen, L = Lost, D = Damaged)';

ALTER TABLE book_copy ADD CONSTRAINT book_copy_pk PRIMARY KEY ( book_copy_sk );

ALTER TABLE book_copy
    ADD CONSTRAINT book_copy_uk UNIQUE ( copy_id,
                                         isbn_no,
                                         branch_code );

CREATE TABLE borrower (
    bor_no      CHAR(8) NOT NULL,
    branch_code CHAR(3) NOT NULL,
    bor_fname   VARCHAR2(50) NOT NULL,
    bor_lname   VARCHAR2(50) NOT NULL,
    bor_address VARCHAR2(100) NOT NULL,
    bor_class   CHAR(1) NOT NULL,
    bor_status  CHAR(1) NOT NULL
);

ALTER TABLE borrower
    ADD CONSTRAINT borrower_class CHECK ( bor_class IN ( 'A', 'C', 'O' ) );

ALTER TABLE borrower
    ADD CHECK ( bor_status IN ( 'B', 'P' ) );

COMMENT ON COLUMN borrower.bor_no IS
    'borrower number';

COMMENT ON COLUMN borrower.branch_code IS
    'branch_code';

COMMENT ON COLUMN borrower.bor_fname IS
    'borrower first name';

COMMENT ON COLUMN borrower.bor_lname IS
    'borrower last name';

COMMENT ON COLUMN borrower.bor_address IS
    'borrower address';

COMMENT ON COLUMN borrower.bor_class IS
    'borrower class (A = adult, C = child, O = organisation)';

COMMENT ON COLUMN borrower.bor_status IS
    'borrower status (P = Permitted, B = Banned)';

ALTER TABLE borrower ADD CONSTRAINT borrower_pk PRIMARY KEY ( bor_no );

CREATE TABLE branch (
    branch_code    CHAR(3) NOT NULL,
    lga_code       CHAR(8) NOT NULL,
    manager_id     CHAR(5) NOT NULL,
    branch_name    VARCHAR2(50) NOT NULL,
    branch_address VARCHAR2(100) NOT NULL,
    branch_phone   CHAR(10) NOT NULL
);

COMMENT ON COLUMN branch.branch_code IS
    'branch_code';

COMMENT ON COLUMN branch.lga_code IS
    'lga code';

COMMENT ON COLUMN branch.manager_id IS
    'manager id';

COMMENT ON COLUMN branch.branch_name IS
    'branch name';

COMMENT ON COLUMN branch.branch_address IS
    'branch address';

COMMENT ON COLUMN branch.branch_phone IS
    'branch contact phone number';

ALTER TABLE branch ADD CONSTRAINT branch_pk PRIMARY KEY ( branch_code );

CREATE TABLE catalogue_entry (
    cat_call_no    VARCHAR2(20) NOT NULL,
    cat_title      VARCHAR2(100) NOT NULL,
    cat_contents   VARCHAR2(1500) NOT NULL,
    classification CHAR(1) NOT NULL,
    cat_pages      NUMBER(6) NOT NULL,
    cat_pub_date   DATE NOT NULL,
    cat_edition    VARCHAR2(15),
    cat_language   VARCHAR2(20) NOT NULL,
    cat_note       VARCHAR2(100),
    reading_level  NUMBER(2)
);

COMMENT ON COLUMN catalogue_entry.cat_call_no IS
    'catalogue call number';

COMMENT ON COLUMN catalogue_entry.cat_title IS
    'catalogue title';

COMMENT ON COLUMN catalogue_entry.cat_contents IS
    'catalogue contents';

COMMENT ON COLUMN catalogue_entry.classification IS
    'classification';

COMMENT ON COLUMN catalogue_entry.cat_pages IS
    'catalogue pages';

COMMENT ON COLUMN catalogue_entry.cat_pub_date IS
    'catalogue publish date';

COMMENT ON COLUMN catalogue_entry.cat_edition IS
    'catalogue edition';

COMMENT ON COLUMN catalogue_entry.cat_language IS
    'catalogue language';

COMMENT ON COLUMN catalogue_entry.cat_note IS
    'catalogue note';

COMMENT ON COLUMN catalogue_entry.reading_level IS
    'reading level';

ALTER TABLE catalogue_entry ADD CONSTRAINT catalogue_entry_pk PRIMARY KEY ( cat_call_no );

CREATE TABLE lga (
    lga_code          CHAR(8) NOT NULL,
    lga_name          VARCHAR2(50) NOT NULL,
    lga_contact_name  VARCHAR2(50) NOT NULL,
    lga_contact_phone CHAR(10) NOT NULL,
    lga_size          NUMBER(8, 2) NOT NULL
);

COMMENT ON COLUMN lga.lga_code IS
    'lga code';

COMMENT ON COLUMN lga.lga_name IS
    'lga name';

COMMENT ON COLUMN lga.lga_contact_name IS
    'lga service contact name';

COMMENT ON COLUMN lga.lga_contact_phone IS
    'lga contact phone number';

COMMENT ON COLUMN lga.lga_size IS
    'lga size in hectare';

ALTER TABLE lga ADD CONSTRAINT lga_pk PRIMARY KEY ( lga_code );

CREATE TABLE loan (
    book_copy_sk      CHAR(3) NOT NULL,
    borrowed_datetime DATE NOT NULL,
    bor_no            CHAR(8) NOT NULL,
    return_datetime   DATE,
    due_back_dt       DATE NOT NULL,
    fine_amnt         NUMBER(5),
    fine_paid_dt      DATE
);

COMMENT ON COLUMN loan.book_copy_sk IS
    'book opy surrograte key';

COMMENT ON COLUMN loan.borrowed_datetime IS
    'borrowed datetime';

COMMENT ON COLUMN loan.bor_no IS
    'borrower number';

COMMENT ON COLUMN loan.return_datetime IS
    'return date time';

COMMENT ON COLUMN loan.due_back_dt IS
    'due back date';

COMMENT ON COLUMN loan.fine_amnt IS
    'fine amount';

COMMENT ON COLUMN loan.fine_paid_dt IS
    'fine paid date';

ALTER TABLE loan ADD CONSTRAINT loan_pk PRIMARY KEY ( borrowed_datetime,
                                                      book_copy_sk );

CREATE TABLE manager (
    manager_id    CHAR(5) NOT NULL,
    branch_code   CHAR(3) NOT NULL,
    manager_fname VARCHAR2(50) NOT NULL,
    manager_lname VARCHAR2(50) NOT NULL,
    manager_phone CHAR(10) NOT NULL
);

COMMENT ON COLUMN manager.manager_id IS
    'manager id';

COMMENT ON COLUMN manager.branch_code IS
    'branch_code';

COMMENT ON COLUMN manager.manager_fname IS
    'manager first name';

COMMENT ON COLUMN manager.manager_lname IS
    'manager last name';

COMMENT ON COLUMN manager.manager_phone IS
    'manager contact phone number';

CREATE UNIQUE INDEX manager__idx ON
    manager (
        branch_code
    ASC );

ALTER TABLE manager ADD CONSTRAINT manager_pk PRIMARY KEY ( manager_id );

CREATE TABLE publisher (
    pub_id       CHAR(4) NOT NULL,
    publisher_nm VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN publisher.pub_id IS
    'publisher id';

COMMENT ON COLUMN publisher.publisher_nm IS
    'publisher name';

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( pub_id );

CREATE TABLE publisher_catalogue (
    pub_id      CHAR(4) NOT NULL,
    cat_call_no VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN publisher_catalogue.pub_id IS
    'publisher id';

COMMENT ON COLUMN publisher_catalogue.cat_call_no IS
    'catalogue call number';

ALTER TABLE publisher_catalogue ADD CONSTRAINT publisher_catalogue_pk PRIMARY KEY ( pub_id,
                                                                                    cat_call_no );

CREATE TABLE reservation (
    reserve_date DATE NOT NULL,
    book_copy_sk CHAR(3) NOT NULL,
    bor_no       CHAR(8) NOT NULL,
    bor_phone    CHAR(10) NOT NULL
);

COMMENT ON COLUMN reservation.reserve_date IS
    'date that book copy was reserved';

COMMENT ON COLUMN reservation.book_copy_sk IS
    'book opy surrograte key';

COMMENT ON COLUMN reservation.bor_no IS
    'borrower number';

COMMENT ON COLUMN reservation.bor_phone IS
    'borrower phone number';

ALTER TABLE reservation
    ADD CONSTRAINT reservation_pk PRIMARY KEY ( reserve_date,
                                                bor_no,
                                                book_copy_sk );

CREATE TABLE subject (
    subject_id   CHAR(4) NOT NULL,
    subject_desc VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN subject.subject_id IS
    'subject id';

COMMENT ON COLUMN subject.subject_desc IS
    'subject description';

ALTER TABLE subject ADD CONSTRAINT subject_pk PRIMARY KEY ( subject_id );

CREATE TABLE subject_catalogue (
    subject_id  CHAR(4) NOT NULL,
    cat_call_no VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN subject_catalogue.subject_id IS
    'subject id';

COMMENT ON COLUMN subject_catalogue.cat_call_no IS
    'catalogue call number';

ALTER TABLE subject_catalogue ADD CONSTRAINT subject_catalogue_pk PRIMARY KEY ( subject_id,
                                                                                cat_call_no );

ALTER TABLE author_catalogue
    ADD CONSTRAINT author_author_catalogue_fk FOREIGN KEY ( auth_id )
        REFERENCES author ( auth_id );

ALTER TABLE book_catalogue
    ADD CONSTRAINT book_book_catalogue_fk FOREIGN KEY ( isbn_no )
        REFERENCES book ( isbn_no );

ALTER TABLE book_copy
    ADD CONSTRAINT book_book_copy_fk FOREIGN KEY ( isbn_no )
        REFERENCES book ( isbn_no );

ALTER TABLE loan
    ADD CONSTRAINT book_copy_loan_fk FOREIGN KEY ( book_copy_sk )
        REFERENCES book_copy ( book_copy_sk );

ALTER TABLE reservation
    ADD CONSTRAINT book_copy_reservation_fk FOREIGN KEY ( book_copy_sk )
        REFERENCES book_copy ( book_copy_sk );

ALTER TABLE loan
    ADD CONSTRAINT borrower_loan_fk FOREIGN KEY ( bor_no )
        REFERENCES borrower ( bor_no );

ALTER TABLE reservation
    ADD CONSTRAINT borrower_reservation_fk FOREIGN KEY ( bor_no )
        REFERENCES borrower ( bor_no );

ALTER TABLE book_copy
    ADD CONSTRAINT branch_book_copy_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE borrower
    ADD CONSTRAINT branch_borrower_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE manager
    ADD CONSTRAINT branch_manager_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE author_catalogue
    ADD CONSTRAINT cat_ent_auth_cat_fk FOREIGN KEY ( cat_call_no )
        REFERENCES catalogue_entry ( cat_call_no );

ALTER TABLE book_catalogue
    ADD CONSTRAINT cat_ent_book_cat_fk FOREIGN KEY ( cat_call_no )
        REFERENCES catalogue_entry ( cat_call_no );

ALTER TABLE publisher_catalogue
    ADD CONSTRAINT cat_ent_pub_cat_fk FOREIGN KEY ( cat_call_no )
        REFERENCES catalogue_entry ( cat_call_no );

ALTER TABLE subject_catalogue
    ADD CONSTRAINT catalogue_entry_fk FOREIGN KEY ( cat_call_no )
        REFERENCES catalogue_entry ( cat_call_no );

ALTER TABLE branch
    ADD CONSTRAINT lga_branch_fk FOREIGN KEY ( lga_code )
        REFERENCES lga ( lga_code );

ALTER TABLE branch
    ADD CONSTRAINT manager_branch_fk FOREIGN KEY ( manager_id )
        REFERENCES manager ( manager_id );

ALTER TABLE publisher_catalogue
    ADD CONSTRAINT pub_pub_cat_fk FOREIGN KEY ( pub_id )
        REFERENCES publisher ( pub_id );

ALTER TABLE subject_catalogue
    ADD CONSTRAINT subject_subject_catalogue_fk FOREIGN KEY ( subject_id )
        REFERENCES subject ( subject_id );


SPOOL off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             1
-- ALTER TABLE                             40
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
